appearance:
  default: system
  switcher: true

theme:
  colorPalettes:
    default:
      light:
        - "#0e79fe"
        - "#45a1bf"
        - "#a5cdee"
        - "#8dacbf"
        - "#85c7c6"
        - "#d2c6ac"
        - "#f4b548"
        - "#8f3d56"
        - "#71b9f4"
        - "#46a485"
      dark:
        - "#0e79fe"
        - "#45a1bf"
        - "#a5cdee"
        - "#8dacbf"
        - "#85c7c6"
        - "#d2c6ac"
        - "#f4b548"
        - "#8f3d56"
        - "#71b9f4"
        - "#46a485"
  colorScales:
    default:
      light:
        - "#ADD8E6"
        - "#00008B"
      dark:
        - "#ADD8E6"
        - "#00008B"
  colors:
    primary:
      light: "#0e79fe"
      dark: "#3b82f6"
    accent:
      light: "#c2410c"
      dark: "#fdba74"
    base:
      light: "#ffffff"
      dark: "#09090b"
    info:
      light: "#0284c7"
      dark: "#38bdf8"
    positive:
      light: "#16a34a"
      dark: "#4ade80"
    warning:
      light: "#f8c900"
      dark: "#fbbf24"
    negative:
      light: "#dc2626"
      dark: "#f87171"

plugins:
  components:
    "@evidence-dev/core-components": {}

  datasources:
    "@evidence-dev/duckdb": { }
    "@evidence-dev/csv": { }
